dataconfig = {
    "classes_all": [
        "002_master_chef_can",
        "035_power_drill",
        "003_cracker_box",
        "004_sugar_box",
        "024_bowl",
        "005_tomato_soup_can",
        "006_mustard_bottle",
        "007_tuna_fish_can",
        "008_pudding_box",
        "009_gelatin_box",
        "010_potted_meat_can",
        "011_banana",
        "019_pitcher_base",
        "021_bleach_cleanser",
        "025_mug",
        "036_wood_block",
        "037_scissors",
        "051_large_clamp",
        "052_extra_large_clamp",
        "061_foam_brick",
        "benchvise",
        "camera",
        "cat",
        "driller",
        "duck",
        "iron",
        "lamp",
        "phone"
    ],
    "classes_easy": [
        "035_power_drill",
        "019_pitcher_base",
        "benchvise",
        "camera",
        "cat",
        "driller",
        "phone"
    ],
}
trainconfig = {
    "inputsize": 128,
    "lr": 0.0001,
    "weightdecay": 0.001,
    "batchsize": 128,
    "epoch": 100,
    "loss_margin": 0.2,
}
